root - ERROR - Traceback (most recent call last):
root - ERROR -   File "C:\Users\NumNu\OneDrive\Bureau\Soft3221 -ass3\Comp3221-Ass3\usage_example.py", line 84, in <module>
root - ERROR -     assert (clients[0].transaction(transaction))
root - ERROR - AssertionError
